/* eslint-disable */
// Generated by scripts/generate-plugin-registry.mjs. Do not edit manually.

import type { RegisteredNodepadPlugin } from "@/lib/plugins"
import { plugin as pluginModule0 } from "@/plugins/blockscape/plugin"
import { plugin as pluginModule1 } from "@/plugins/markdown-import/plugin"

export const GENERATED_PLUGINS: RegisteredNodepadPlugin[] = [
  {
    manifest: {
      "id": "blockscape",
      "label": "Blockscape",
      "description": "Structured graph view plus Blockscape JSON export",
      "enabledByDefault": false
    },
    module: pluginModule0
  },
  {
    manifest: {
      "id": "markdown-import",
      "label": "Markdown Import",
      "description": "Append Markdown files into the current project",
      "enabledByDefault": false
    },
    module: pluginModule1
  }
]
