/* eslint-disable */
// Generated by scripts/generate-plugin-registry.mjs. Do not edit manually.

import type { RegisteredNodepadPlugin } from "@/lib/plugins"
import { plugin as pluginModule0 } from "@/plugins/blockscape/plugin"

export const GENERATED_PLUGINS: RegisteredNodepadPlugin[] = [
  {
    manifest: {
      "id": "blockscape",
      "label": "Blockscape",
      "description": "Structured graph view plus Blockscape JSON export",
      "enabledByDefault": false
    },
    module: pluginModule0
  }
]
